- main.py
This PR fixes #12.
Description of the change
-----------------------------
A fix was implemented to prevent race conditions when multiple request to create flows are received in parallel (or concurrent with the consistency check routine). The unit tests were run and all of them are passing. The end-to-end tests were also run, including the new ones to validate this specific situation (repeated 10 times), all of them are passing (except the ones not related to this PR).
The fix is based on two modifications: 1) use of Thread.Locks as a way to orchestrated the usage of shared resources and avoid race-condition (in this case the shared resource is the storehouse); 2) a new `save` flag introduced in the `_install_flows()` function which enables or disables the persistency of the flows being …
> Fix race condition when handling multiple concurrent requests

- main.py
- tests/unit/test_main.py
Fixes #20 and #21.
POST and DELETE methods were returning 200 but should return 202 when the NApp sucessfully send the flows to the switches.
They don't return 201 because as the communication with the switch is asynchronous there is no answer from the switch to be returned to the client.
> Change POST and DELETE return codes

- main.py
- match.py
- requirements/dev.in
- requirements/dev.txt
- serializers/base.py
- serializers/v0x01.py
- serializers/v0x04.py
- setup.cfg
- setup.py
- storehouse.py
- tests/__init__.py
- tests/integration/test_main.py
- tests/unit/test_flow_serializer_v0x01.py
- tests/unit/test_flow_serializer_v0x04.py
- tests/unit/test_main.py
- tests/unit/test_storehouse.py
I have some upcoming fixes for flow_manager that we have planned, and to minimize code formatting changes as the team has agreed, I'm sending a prior prior just related to enabling and formatting the code with [`black`](https://github.com/psf/black). I'll document in this PR how it can be introduced on other NApps as well, and then in the future we can evolve setting up pre-commit hooks as well: 
- Add it as a dependency on `requirements/dev.in` (we'll try to get it as a linter on `yala` upstream), and make sure that the `Linter.run()` method on `setup.py` is also passing the python files to be check, see f19131ae28451cf9b311ba8652ab81115a319800
- Make sure to update `setup.cfg` file accordingly that `yala` uses, just so `isort` plays nicely with `black`, it needs the `black` profile, and …
> Added `black` as a dev linter dependency and formatted with it

- requirements/dev.txt
- setup.py
I'm bumping `yala` to version [`3.1.0`](https://github.com/cemsbr/yala/releases/tag/v3.1.0). Cadu has accepted and helped out to add `black` as a linter: 
```
running lint
Yala is running. It may take several seconds...
INFO: Finished isort
INFO: Finished pycodestyle
INFO: Finished black
INFO: Finished pylint
[isort] Skipped 5 files
:) No issues found.
```
> Updated requirements/dev.txt to run black via yala

- tests/unit/test_main.py
This PR fixes #10
and also `**R8)** The consistency check routine should keep track of all OpenFlow tables, not just table 0, unless there is a setting to ignore an specific table.` from EP24 . 
**No additional changes were needed to support this**, but since I was verifying the unit test that covered this, took the chance to add a `subTest` as we've done for pathfinder when iterating over a range of expected values https://github.com/kytos-ng/pathfinder/pull/1#discussion_r733969128
> Updated ignore table ids and cookie ranges unit tests with `subTest`

- CHANGELOG.rst
- kytos.json
- main.py
- match.py
- setup.py
- tests/unit/test_main.py
Fixes #23 that @italovalcy has reported 
- This PR is same as PR #42 (but I'm using the `fix/overlapping_flows` branch directly on the upstream repo to facilitate visualizing diffs since there are upcoming PRs that will depend on this branch here, let's try this out to see if it facilitates for us)
- Augmented ``_add_flow_store`` to overwrite overlapping flows
- Added unit test to cover it
> [Fix] Overlapping stored flows 

- CHANGELOG.rst
- kytos.json
- main.py
- openapi.yml
- setup.cfg
- setup.py
- tests/unit/test_main.py
- utils.py
Fixes #46 
- Added support for ``force`` option when sending flow mods
Once this change lands, clients can decide reliably if they want to ``force`` the flow mode to be sent later on (via consistency check) in case any switch connection errors happened as the flows were being installed. So, it's up to each client to decide if the client wants the flows to be either forced or not, for example, if `mef_eline` wants the flows being installed or fail immediately in case a switch isn't connected, then set `force: false`, for applications that don't care when the flow should be installed, and there's no other potential paths that the client could make of use then setting `force: true` would be handy. 
Notice that errors could still happen even when `force: true` is set (for instance, imagine a …
> [Feature] Added support for `force` option when sending flow mods

- CHANGELOG.rst
- exceptions.py
- kytos.json
- main.py
- setup.cfg
- setup.py
- tests/unit/test_main.py
- utils.py
Fixes #2  
This PR added support to publish the rest of flows events to support reliably publishing events when flows are added, removed, still pending (not confirmed yet), and also handled switch connection error `kytos/core.openflow.connection.error` to bubble up the error to the caller. So, now `flow_manager` clients will be able to react accordingly and handle each event as needed based on their use case, not necessarily all clients will have to react and handle, but as they need, the events to completely handle every case are available, [handling the `kytos/flow_manager.flow.error` event is highly encouraged though at least, as `mef_eline` already does](https://github.com/kytos-ng/mef_eline/blob/master/main.py#L664-665).
`version [5.3.0] - 2021-11.21`
- Started listening to …
> [Feature] Generate flow events for every flow added or removed

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #32
- Added thread concurrency control execution per switch when executing `check_consistency`. I ended up using the `STATS_INTERVAL / 2` as a reference to skip executions per switch, without using this a reference it could still end up with cases where it would still execute relatively close to previous executions, so this enforces some back pressure.
> [Feature] consistency_check concurrency execution control 

- CHANGELOG.rst
- barrier_request.py
- kytos.json
- main.py
- settings.py
- setup.py
- tests/unit/test_main.py
Fixes #7
Added support for barrier request
`version [5.5.0] - 2021-11.24`
- Added support for ofpt_barrier_request and ofpt_barrier_reply
- Mapped barrier reply xid with flow mod xid to correlate them, and to also to confirm installed flows in an event-driver manner.
- Stored in memory errors of flow mod xids to correlate them when a barrier reply is received.
- Added thread locks accordingly for the dictionaries used.
- Added support to delete the stored_flow once an ofpt_error when receiving a barrier reply, to avoid this flow to keep being sent via consistency check.
With barrier request and reply, now we can confirm more promptly (event-driven) a flow mod xid without exclusively depending on the consistency check routine:
1) Example when an ofpt_error happens (once clients implement …
> [Feature] Added support for barrier request

- CHANGELOG.rst
- exceptions.py
- kytos.json
- main.py
- setup.cfg
- setup.py
- tests/unit/test_main.py
Same as PR #54 but correctly targeting `master` this time, it turns out that GH didn't delete the `feature/c_check_concurrency_control` branch and I merged into that branch instead, it was supported to target `master` though. @italovalcy if you could review again, thanks
I suppose we could also active the automatic deletion of branches once it's merged to avoid another PR to merge into it again, that way it should correctly target `master` again once the child branch has landed. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches
> [Feature] Barrier request

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #57 
- Added an upper bound rotating limit for the number of barrier replies, [like we have for flow mods](https://github.com/kytos-ng/flow_manager/blob/master/main.py#L721) stored in memory. In the future, this will be moved to a NoSQL DB.
- Changed ``_flow_mods_sent_error_locks``, ``_pending_barrier_locks``, and ``_check_consistency_lock`` to be safer using a single lock based on what we currently have
> [Feature] Added an upper rotating limit for barrier replies

- .coveragerc
- CHANGELOG.rst
- kytos.json
- main.py
- settings.py
- setup.py
- tests/unit/test_main.py
- tests/unit/test_utils.py
- utils.py
Fixes #56 
Added support for asynchronously retrying temporary connection errors from `kytos/core.openflow.connection.error`, and publishing a `kytos/flow_manager.flow.error` error with a key `error_exception` set, that way enhancing handling potential connection outages and facilitating for subscribers in terms of temporary error handling, so up to this point, whenever subscribers get a `kytos/flow_manager.flow.error` they can differentiate and react accordingly. 
`[5.7.0] - 2021-12-15`
- Added support for retrying ``kytos/core.openflow.connection.error``
- Added retry configuration options with default values
Here's an execution simulating connection errors when `mef_eline` is trying to create an EVC: 
```
2021-12-17 16:32:36,520 - INFO [kytos.napps.kytos/flow_manager] …
```
> [Feature] Retry connection errors before sending `kytos/flow_manager.flow.error`

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #63 
Avoid skipping consistency check right after a reconnection
- Subscribed to ``on_connection_lost`` event to reset consistency check executions
- Now, after a reconnection, once the consistency check runs again, it won't skip:
```
2022-01-18 15:10:09,225 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:56106
2022-01-18 15:10:09,226 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:56108
2022-01-18 15:10:09,228 - INFO [kytos.core.atcp_server] (MainThread) New connection from 127.0.0.1:56110
2022-01-18 15:10:09,244 - INFO [kytos.napps.kytos/of_core] (ThreadPoolExecutor-0_9) Connection ('127.0.0.1', 56108), Switch 00:00:00:00:00:00:00:03: OPENFLOW HANDSHAKE COMPLETE
2022-01-18 15:10:09,259 - INFO [kytos.napps.kytos/of_core] …
```
> [Fix] Avoid skipping consistency check after a reconnection

- README.rst
Updated the README.rst, now it has the same shields as `mef_eline`, and also, [you can view the rendered readme visiting this page](https://github.com/kytos-ng/flow_manager/tree/fix/update_readme):
- Added a centralized header component with a link to this NApp's OpenAPI spec 
- Added which major features are supported
- Updated events
- Updated how to install
> [Fix] Updated README.rst 

- CHANGELOG.rst
- kytos.json
- setup.py
- storehouse.py
Fix #67 
This PR adds a `threading.Lock` mechanism to protect flow_manager's storehouse from race conditions in the save flows. The general idea of Lock protection follows the same logic already adopted by mef_eline and topology. 
After applying this PR, new tests were run to confirm the fix of issue #67 (following the same methodology described at kytos-ng/storehouse#9). Out of 20 repetitions, no failure was observed.
- Added Lock mechanism to protect flow_manager's  storehouse from race conditions.
> Add Lock to prevent race conditions at flow_manager.storehouse

- CHANGELOG.rst
- kytos.json
- main.py
- settings.py
- setup.cfg
- setup.py
- tests/unit/test_main.py
- utils.py
Fixes #69 
This PR introduced an optimization opportunity that @italovalcy [has found on this comment](https://github.com/kytos-ng/flow_manager/issues/69#issuecomment-1030370568), so, now in the same way that consistency tries to skip a pass if a recent flow was added it's doing the same thing for recent deleted flows. I've also cherry picked some commits from PR #45, that I worked sometime ago for archived flows, however, the main difference to avoid putting more pressure on store house is that I only kept the parts we'd need for this feature with storage in memory, so no additional IO/DB pressure is expected. I think it's a win-win situation since now we've got the archived flows partly landed as well, and then when we have a new NoSQL backend it's a matter of writing and reading from …
> [Fix] Optimization in the consistency check to skip recent deleted flows 

- main.py
- requirements/dev.txt
- setup.py
- tests/unit/test_main.py
Fixes #84 
- Update setup to make flow_manager compatible with py39, as per comment https://github.com/kytos-ng/flow_stats/pull/18#discussion_r852213307
- Adding conditional to install dataclasses only on python < 3.7 (PEP 557)
- Fix dependency conflicts with kytos (typing-extensions)
- Fix unit tests that were failing after first call due to threaded listen_to methods direct call (using the strategy of on_event/handle_event)
- Adding a few unit tests to increase coverage
N/A
> Update setup and dependencies to be compatible with py39 and fix conflicts

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- setup.cfg
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
- tests/unit/test_match_13.py
- tests/unit/test_utils.py
- utils.py
Fixes #80 
- Refactored `flows` upsert and delete operations to use `bulk_write` instead for higher performance based on the expected workload
- Endpoint /flow_manager/v2/flows/ writes first to the database now to optimize consistency for bulk operations
This table summarize the ratio of performance gains comparing this branch `feature/bulk_ops` with `feature/mongo`, the number of DB operations are no longer proportional of the number of flows in the body but constant to the number of the request. For upserts (update or insert) with 3 flows, the gains are significant, 100x faster comparing the 95 percentile. For deletions, it's 10x faster comparing the 95 percentile. For a single flow it's relatively the same:
To measure the performance, it was stress tested with 50 req / sec during 60 …
> [Feature] MongoDB `bulk_write` operations for `/api/kytos/flow_manager/v2/flows/`

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes #86 
- Added log.info entry for kytos.flow_manager.flows.(install|delete) handler for troubleshooting, same as flow_manaer has for the `/flows` endpoint
For more info, checkout [this thread](https://github.com/kytos-ng/flow_manager/pull/82#discussion_r886101436) that @italovalcy and I were exchanging ideas about this log. 
```
kytos $> 2022-05-31 18:55:03,069 - INFO [kytos.napps.kytos/flow_manager] (thread_pool_app_3) Send FlowMod from KytosEvent dpid: 00:00:00:00:00:00:00:01, command: delete, force: False,
flows_dict: {'flows': [{'cookie': 12254757024401928266, 'cookie_mask': 18446744073709551615}]}
2022-05-31 18:55:03,070 - INFO [kytos.napps.kytos/flow_manager] (thread_pool_app_7) Send FlowMod from KytosEvent dpid: 00:00:00:00:00:00:00:03, command: delete, force: False, …
```
> [Feature] log.info entry for `kytos.flow_manager.flows.(install|delete)` handler for troubleshooting

- main.py
- tests/unit/test_main.py
Fixes #95 
Added support for unloaded switch version falling back to Flow04 on FlowFactory.get_class [that is available on this PR](https://github.com/kytos-ng/of_core/pull/74). It fallsback to Flow04 since this is the major version we plan to have support for the foreseeable future, we could also try to restore `ofp_version` but it's not worth it considering it would need extra changes and considering the direction with gRPC and P4 that our team will support. 
If you repeat the original corner case it doesn't crash anymore and it returns 424 as expected or 202 if the `force` option is used:
```
❯ echo '{"force": false, "flows": [ { "match": { "in_port": 1 }, "actions": [ { "action_type": "output", "port": 2 } ] } ] }' | http POST http://localhost:8181/api/kytos/flow_manager/v2/ …
```
> [Fix] Added support for unloaded switch version falling back to Flow04

- controllers/__init__.py
- main.py
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
Fixes #100, thanks for reporting and catching this @italovalcy
- Replaced `get_flows_lte_inserted_at` with `get_flows_lte_updated_at`
- Fixed missing flows to consider `updated_at` instead of `inserted_at`
- Fixed alien flows to skip if it's comparing with a recent updated flow
I didn't update the changelog since this bug has been introduced in this unreleased/development version. 
Using a similar case that Italo has provided:
- If you install an overlapping flow at the right time when the consistency check is checking for alien flows it'll skip it (I added also a temporary log to facilitate understanding `skipping alien`):
```
2022-08-05 14:50:21,947 - INFO [kytos.napps.kytos/flow_manager] (thread_pool_sb_2) check_consistency on switch 00:00:00:00:00:00:00:01 has started
kytos $> …
```
> [Fix] Consistency check to avoid deleting certain recent changes

- CHANGELOG.rst
- README.rst
- controllers/__init__.py
- db/models/__init__.py
- main.py
- settings.py
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
This is on top of PR #101. It fixes the rest of the issues that have been surfaced, thanks @italovalcy for spotting newer ones on production-like environment. In summary (more details available on changelog if you need):
1 - **Added `CONSISTENCY_MIN_VERDICT_INTERVAL` on settings.py**:
Granular control for the minimum expected interval that consistency check should wait before detecting inconsistencies, after skipping recent updates or deletions. Each consistency execution will now keep track of when it was last run without assuming that it was run within `STATS_INTERVAL`, switches can get overloaded. Each execution is still driven by ``kytos/of_core.flow_stats.received`` though. This interval is recommended to be at lest greater than `FLOW_STATS` interval and ideally slightly greater than …
> [Fix] Consistency check fixes part 2

- main.py
Fixes #106 
- Extracted resend_stored_flows for testability, it was using `listen_to`
In the future, we'll likely have better support on kytos core to have testability for this methods decorated with `listen_to`, in the meantime, following the existing pattern of extracting a new method at a expense of losing a few statements of unit code cov. 
I didn't add anything on changelog since this is just refactoring for testability.
> [Fix] Extracted resend_stored_flows for testability

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
Fixed #112 
Endpoints GET v2/stored_flows and GET v2/stored_flows/<dpid> have been added for listing flows from flows collection.
Note that the _id from the database model has been excluded in the response. Also, query parameter filter for state is supported.
Example:
http://localhost:8181/api/kytos/flow_manager/v2/stored_flows?state=pending
{
"00:00:00:00:00:00:00:01": {
"flows": []
},
"00:00:00:00:00:00:00:02": {
"flows": []
},
"00:00:00:00:00:00:00:03": {
"flows": []
}
}
http://localhost:8181/api/kytos/flow_manager/v2/stored_flows/00:00:00:00:00:00:00:01
{
"00:00:00:00:00:00:00:01": {
"flows": [
{
"flow": {
"actions": [
{
"action_type": "push_vlan",
"tag_type": "s"
},
{
"action_type": "set_vlan",
"vlan_id": 3824
},
{
"action_type": "output",
"port": 2
}
],
"cookie": …
> Adding endpoints for stored flows

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes #114 
- Fixed consistency check to run immediately when FlowStats is first received.
- Once FlowStats is first received and consistency check started, after 4ms in the same cycle, it detected a missing flow:
```
kytos $> 2022-10-24 11:02:58,745 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:57598
2022-10-24 11:02:58,746 - INFO [kytos.core.atcp_server] [atcp_server.py:182:connection_lost] (MainThread) Connection lost with client 127.0.0.1:57598. Reason: Request closed by client
2022-10-24 11:02:58,851 - INFO [kytos.core.atcp_server] [atcp_server.py:131:connection_made] (MainThread) New connection from 127.0.0.1:57612
2022-10-24 11:02:58,858 - INFO [kytos.napps.kytos/of_core] [main.py:138:handle_features_reply] …
```
> [Fix] Consistency check to run immediately when FlowStats is first received

- CHANGELOG.rst
- db/models/__init__.py
- tests/unit/test_db_models.py
Fixes #117 
This PR is on top of PR #115 
Thanks @italovalcy for catching this, and the initial patch. 
With this PR I provisioned one EPL to make sure no other side effects happend, worked as usual. 
```
2022-10-31 13:07:45,463 - INFO [kytos.napps.kytos/mef_eline] [evc.py:672:deploy_to_path] (Thread-100) EVC(5cac9d46e6fc41, epl) was deployed.
```
@italovalcy it'd be great if you could try out this branch in the original scenario, thanks.
> [Fix] FlowSubDoc model `instructions`

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes #120 
- Handled connection exception corner case before an OpenFlow handshake. If the connection isn't set yet, then it'll fallback to version 0x04, same approach that we have on our `FlowFactory`.
Explored it locally, the API response status code behaves as you'd expect `202` or `424`:
```
kytos $> controller.switches['00:00:00:00:00:00:00:01'].connection = None
kytos $> 2022-11-10 17:48:53,435 - INFO [kytos.napps.kytos/flow_manager] [main.py:589:_send_flow_mods_from_request] (Thread-140) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01
, command: add, force: False, flows_dict: {'force': False, 'flows': [{'priority': 101, 'match': {'in_port': 1, 'dl_vlan': 105}, 'actions': [{'action_type': 'output', 'port': 1}]}]}
2022-11-10 17:48:53,476 - INFO [werkzeug] …
```
> [Fix] AttributeError: 'NoneType' object has no attribute 'protocol'

- controllers/__init__.py
- main.py
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
- tests/unit/test_utils.py
- utils.py
Closes #129
- Fixed `cookie_mask` query to match a range of cookies. 
- Implemented the query solution mentioned on this comment https://github.com/kytos-ng/flow_manager/issues/129#issuecomment-1363206096, aggregating the (merged) cookie ranges with an `"$or"` operator, I've also checked on MongoDB that the index is being hit correctly.
Also, to recap, FYI, flow_manager still doesn't validate completely the payload on this endpoint, so invalid type or values can lead to issues, but that will be covered on issue #43
I've added three new e2e tests to cover the ranges with `cookie_mask` on another PR https://github.com/kytos-ng/kytos-end-to-end-tests/pull/197, to also cover the original issue that Italo has caught, and ran `flow_manager` related tests again:
```
+ python3 -m pytest tests/ …
```
> [fix] Fixed `cookie_mask` query to match a range of cookies

- CHANGELOG.rst
- kytos.json
- main.py
- tests/unit/test_main.py
Closes #136 
Related to https://github.com/kytos-ng/of_core/issues/102
Tested out a request with a overflowed cookie
```
{
"code": 400,
"description": "FlowMod.cookie - Expected UBInt64, found value \"27115650311270694912\" of type int",
"name": "Bad Request"
}
```
I'll run with the rest of the related changes
> feat: release 2022.3.1: handled PackException to return bad request if a flow can't be packed

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Closes #131 
This PR is on top of PR #137 since both will land as a patch for 2022.3.1
I simulated OpenFlow connection errors in addition to the unit tests, the retries went as expected:
```
kytos $> 2023-02-20 18:25:53,402 - INFO [kytos.napps.kytos/flow_manager] [main.py:603:_send_flow_mods_from_request] (Thread-103) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01,
command: add, force: False, flows_dict: {'force': False, 'flows': [{'priority': 101, 'cookie': 100, 'match': {'in_port': 1}, 'actions': [{'action_type': 'output', 'port': 2}]}]}
2023-02-20 18:25:53,408 - INFO [kytos.core.controller] [controller.py:640:msg_out_event_handler] (MainThread) connection closed. Cannot send message
2023-02-20 18:25:54,412 - INFO [kytos.napps.kytos/flow_manager] …
```
> fix: release 2022.3.1: Fixed not iterable error when sending a FlowMod during OpenFlow connection

- CHANGELOG.rst
- controllers/__init__.py
- openapi.yml
- tests/unit/test_flow_controller.py
Closes #139 
Sort the flows that are obtained with a request of stored flows with [`find_flows`](https://github.com/kytos-ng/flow_manager/blob/3957bdc61af593b536b39313b3e32d0473a6c597/controllers/__init__.py#L202-L204)
Requiest: 
```
http://127.0.0.1:8181/api/kytos/flow_manager/v2/stored_flows?dpid=00:00:00:00:00:00:00:02&state=installed
```
Response:
```
{
"00:00:00:00:00:00:00:02": [
{
"flow": {
"actions": [
{
"action_type": "set_vlan",
"vlan_id": 4001
},
{
"action_type": "output",
"port": 3
}
],
"cookie": 12310228866111668291,
"hard_timeout": 0,
"idle_timeout": 0,
"match": {
"dl_vlan": 3824,
"in_port": 2
},
"priority": 32768,
"table_id": 0
},
"flow_id": "c7d11070198ebad1796b22c6d215c74b",
"id": "dee0f288ec9aed48d4ce2d466ebf7e46",
"inserted_at": "2022-09-22T21:00:44",
"state": …
```
> feature: Sort the stored flows returned with `flow_manager/v2/stored_flows`

- CHANGELOG.rst
- exceptions.py
- main.py
- tests/unit/test_main.py
- tests/unit/test_utils.py
- utils.py
Closes #146
Closes #91 
- Created one EVC, simulated link down and EVC removal:
```
kytos $> 2023-05-11 14:53:20,132 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:46284 - "POST /api/kytos/mef_eline/v2/evc/ HTTP/1.1" 400                    
2023-05-11 14:56:05,093 - INFO [kytos.napps.kytos/mef_eline] [evc.py:805:setup_failover_path] (thread_pool_app_4) Failover path for EVC(c96386c0dfe243, epl) was deployed.
2023-05-11 14:56:40,654 - INFO [kytos.napps.kytos/mef_eline] [main.py:706:handle_link_down] (thread_pool_app_2) Event handle_link_down Link(Interface('s1-eth4', 4, Switch('00:00:00:00:0
0:00:00:01')), Interface('s3-eth3', 3, Switch('00:00:00:00:00:00:00:03')))
2023-05-11 14:56:40,655 - INFO [kytos.napps.kytos/flow_manager] …
```
> feat: basic validation for ``cookie`` and ``cookie_mask`` when installing or removing flows.

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/unit/test_flow_controller.py
Closes #152 
```
❯ http 'http://0.0.0.0:8181/api/kytos/flow_manager/v2/stored_flows?state=installed' | jq | grep state       
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
"state": "installed",
```
```
❯ http 'http://0.0.0.0:8181/api/kytos/flow_manager/v2/stored_flows?state=installed&state=deleted' | jq | grep state
"state": "installed",
"state": "installed",
"state": "deleted",
"state": "deleted",
"state": …
```
> feat: augmented `GET v2/stored_flows` state query filter to support a list of values

- CHANGELOG.rst
- tests/unit/test_match_13.py
- v0x04/match.py
Closes #155 
Flows with different flows were being marked to be deleted. This was because `table_id` was not being checked. Added a condition to compare `table_id` values when necessary.
Installed flows through POST `http://localhost:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01`:
```
{
"force": false,
"flows": [
{
"priority": 40000,
"cookie": 100,
"table_id": 0,
"instructions": [
{
"instruction_type": "goto_table",
"table_id": 1
}
]
},
{
"priority": 40000,
"cookie": 100,
"table_id": 1,
"instructions": [
{
"instruction_type": "goto_table",
"table_id": 2
}
]
}
]
}
```
Deleteting with DELETE `http://localhost:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:01`, should only delete 1 flow:
```
{
"force": false,
"flows": [
{
"priority": 40000,
"table_id": 0,
"cookie": …
```
> fix: Added table_id checking when matching flows

- CHANGELOG.rst
- controllers/__init__.py
- scripts/README.md
- scripts/drop_compound_index.py
- tests/unit/test_flow_controller.py
Closes #160 
I'll send a backport to `2022.3.2` shortly
See updated changelog for more information
- On version `2022.3.2` I ran this script:
```
❯ CMD=drop_index python3 drop_compound_index.py      
None
```
If you try to run again, it'll error out as expect since the index `switch_1_flow.cookie_1_state_1_inserted_at_1_updated_at_1` doesn't exist anymore:
```
❯ CMD=drop_index python3 drop_compound_index.py
pymongo error: index not found with name [switch_1_flow.cookie_1_state_1_inserted_at_1_updated_at_1], full error: {'ok': 0.0, 'errmsg': 'index not found with name [switch_1_flow.cookie_1
_state_1_inserted_at_1_updated_at_1]', 'code': 27, 'codeName': 'IndexNotFound', '$clusterTime': {'clusterTime': Timestamp(1691420918, 2), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00 …
```
> chore: added scripts/drop_compound_index.py

- CHANGELOG.rst
- db/models/__init__.py
- main.py
- setup.cfg
- tests/unit/test_db_models.py
- tests/unit/test_main.py
Closes #159 
When adding a flow, `actions` and `instructions` should not be present at the same time.
Created requests with `actions` and `instructions` in the same flow.
Added uni tests
> Added validator for `actions` and `instructions`

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
- tests/unit/test_utils.py
- utils.py
Closes #165 
Query latency reasonable as expected on APM:
Also, sent a few requests exploring the parameters, worked as expected:
```
❯ http 'http://0.0.0.0:8181/api/kytos/flow_manager/v2/stored_flows?cookie_range=1&cookie_range=2&cookie_range=10&cookie_range=13'
HTTP/1.1 200 OK
content-length: 2489
content-type: application/json
date: Tue, 08 Aug 2023 19:25:46 GMT
server: uvicorn
{
"00:00:00:00:00:00:00:01": [
{
"flow": {
"actions": [
{
"action_type": "output",
"port": 2
}
],
"cookie": 13,
"hard_timeout": 0,
"idle_timeout": 0,
"match": {
"dl_vlan": 13,
"in_port": 1
},
"priority": 13,
"table_group": "base",
"table_id": 0
},
"flow_id": "5b0cf6c243d8f318051d758a9acfd4db",
"id": "f5de0eb1c875b49837ecd58b687c72c9",
"inserted_at": "2023-08-08T19:23:35.052000", …
```
> feat: updated v2/stored_flows cookie_range to accept an even list of ranges

- CHANGELOG.rst
- controllers/__init__.py
- kytos.json
- scripts/README.md
- scripts/drop_compound_index.py
- tests/unit/test_flow_controller.py
Backported from PR #162 
Upgraded from `2022.3.1` to `2022.3.3`:
```
rs0 [direct: primary] napps> db.flows.getIndexes()
[
{ v: 2, key: { _id: 1 }, name: '_id_' },
{
v: 2,
key: { flow_id: 1 },
name: 'flow_id_1',
background: true,
unique: true
},
{
v: 2,
key: { 'flow.cookie': 1 },
name: 'flow.cookie_1',
background: true
},
{ v: 2, key: { state: 1 }, name: 'state_1', background: true },
{
v: 2,
key: {
switch: 1,
'flow.cookie': 1,
state: 1,
inserted_at: 1,
updated_at: 1
},
name: 'switch_1_flow.cookie_1_state_1_inserted_at_1_updated_at_1',
background: true
}
]
rs0 [direct: primary] napps> db.flows.countDocuments()
1003
```
- Ran the script, and confirmed the index deletion:
```
❯ CMD=drop_index python3 drop_compound_index.py
None
```
```
rs0 [direct: primary] napps> db.flows.getIndexes()
[
{ …
```
> chore: release 2022.3.3: added scripts/drop_compound_index.py

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Closes #173, thanks @italovalcy and Renata for catching and reporting this
Without this branch and with `settings.ENABLE_BARRIER_REQUEST = False` to help to simulate an equivalent scenario (just so the installed state didn't get update as a consequence of a barrier reply):
```
rs0 [direct: primary] napps> db.flows.find({"state": "pending", "switch": "00:00:00:00:00:00:00:01"}, {"id": 1, "match_id": 1, "state": 1, "switch": 1, "flow": 1})
[
{
_id: 'b33f354ca83bfc990537e1d8d0c964e4',
flow: {
owner: 'of_lldp',
cookie: Decimal128("12321848580485677057"),
match: { dl_type: 35020, dl_vlan: 3799 },
actions: [ { action_type: 'output', port: Long("4294967293") } ],
table_id: 0,
table_group: 'base',
priority: 50000,
idle_timeout: 0,
hard_timeout: 0
},
id: …
```
> fix: fixed updating flow installed state via `kytos/of_core.flow_stats.received`

- CHANGELOG.rst
- kytos.json
- main.py
- tests/unit/test_main.py
Backport of PR #174 for `2023.1` bumping version `2023.1.1`
I explored locally with the same test as the linked PR
See related PR
> [2023.1.1][backport] fix: fixed updating flow installed state via `kytos/of_core.flow_stats.received`

- CHANGELOG.rst
- main.py
- openapi.yml
- tests/unit/test_main.py
Closes #176 
- See updated changelog file
- For more information why this is needed/recommended, check out [this comment](https://github.com/kytos-ng/flow_manager/issues/176#issuecomment-1833971281)
- Explored locally setting the json body, worked as expected, it's reusing the same underlying transformations.
```
+ python3 -m pytest tests/ --reruns 2 -r fEr
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
rootdir: /builds/amlight/kytos-end-to-end-tester/kytos-end-to-end-tests
plugins: rerunfailures-10.2, timeout-2.1.0, anyio-3.6.2
collected 254 items
tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py .................. …
```
> feat: `cookie_range` filter via body too

- CHANGELOG.rst
- README.rst
- main.py
- tests/unit/test_main.py
Closes #185 
See updated changelog file 
- Tested out the same issue, no longer happens. 
- Also used it with `telemetry_int` and `iperf`, it's performing well (5k packets re transmissions in the data plane with failover - which is similar to prior convergence measurements for this kind of network failure / sending flows mods):
```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec  65.0 GBytes  9.31 Gbits/sec  5578             sender
[  4]   0.00-60.00  sec  65.0 GBytes  9.30 Gbits/sec                  receiver
```
```
2024-06-13 11:49:40,064 - INFO [kytos.napps.kytos/flow_manager] (dynamic_single_0) Send FlowMod from KytosEvent dpid: 00:00:00:00:00:00:00:06, command: add, force: True,  flows[0, 7]: …
```
> feat: added kytos.flow_manager.flows.single.(install|delete) handler

- CHANGELOG.rst
- main.py
- setup.py
- tests/unit/test_main.py
- utils.py
Closes #192
Closes #104
Added log for number of flows and force option
Added condition for empty list of flows for events.
Created EVCs to see the logging
N/A
> Adding log for number of flows

- scripts/db/2023.1.0/001_pipeline_related.py
Closes #203 
- Fixed db migration script `2023.1.0/001_pipeline_related.py` with the correct DB name from MONGO_DBNAME env var
N/A
N/A
> fix dbname for mongo client based on MONGO_DBNAME env var

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
Closes #209 
- Only update flows as ``'installed'`` if they were ``'pending'``. This fixed processing late barrier replies correctly even if there was a recent related flow deletion.
- Ran the same as issue #209, it no longer happens
```
kytos $> 2024-11-01 14:30:09,389 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: add, force: False, tota
l_length: 1,  flows[0, 1]: [{'match': {'in_port': 1, 'dl_vlan': 200}, 'instructions': [{'instruction_type': 'apply_actions', 'actions': [{'action_type': 'output', 'port': 2}]}]}]
2024-11-01 14:30:09,398 - INFO [uvicorn.access] (MainThread) 127.0.0.1:50586 - "POST /api/kytos/flow_manager/v2/flows/00%3A00%3A00%3A00%3A00%3A00%3A00%3A01 HTTP/1.1" 202
2024-11-01 14:30:09,405 - …
```
> fix: only update flows as `'installed'` if they were `'pending'`

- CHANGELOG.rst
- controllers/__init__.py
- kytos.json
- main.py
Closes #210 
See https://github.com/kytos-ng/flow_manager/pull/211 for more information
```
WARNING kytos (2024.1.2) and kytos utils (2024.1.0) versions are not equal.
Status |           NApp ID            |                                    Description                                   
=======+==============================+==================================================================================
[ie]  | amlight/sdntrace_cp:2024.1.0 | Run tracepaths on OpenFlow in the Control Plane                                  
[ie]  | kytos/flow_manager:2024.1.3  | Manage switches' flows through a REST API.                                       
[ie]  | kytos/mef_eline:2024.1.5     | NApp to provision circuits from user request                                     
[ie]  | …
```
> [release 2024.1.3] fix: only update flows as `'installed'` if they were `'pending'`

- README.rst
---
- Added kytos/flow_manager.messages.out.ofpt_barrier_request to README
- Added kytos/flow_manager.messages.out.ofpt_flow_mod to README
Closes #207 
Two events were not mentioned in the README, as mentioned in issue 207. This MR seeks to update the README with the new events appended to the "Generated" section.
> Issue 207 - Append unmentioned events to README

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/unit/test_flow_controller.py
- tests/unit/test_main.py
- tests/unit/test_utils.py
- utils.py
Closes #202 
Added requests for installation and deletion flows and specified switches in the content:
- `POST .../api/kytos/flow_manager/v2/flows/flows_by_switch` with content as:
```
{
"00:00:00:00:00:00:00:03": {
"flows": [{"match": {"in_port": 3, "dl_vlan": 1}, "cookie": 12297829382473034410, "actions": [{"action_type": "set_vlan", "vlan_id": 1}, {"action_type": "output", "port": 2}], "owner": "mef_eline", "table_group": "evpl", "table_id": 0, "priority": 20000}, {"match": {"in_port": 2, "dl_vlan": 1}, "cookie": 12297829382473034410, "actions": [{"action_type": "set_vlan", "vlan_id": 1}, {"action_type": "output", "port": 3}], "owner": "mef_eline", "table_group": "evpl", "table_id": 0, "priority": 20000}]
},
"00:00:00:00:00:00:00:02": {
"flows": [{"match": {"in_port": 3, "dl_vlan": 1}, …
```
> Added requests for flows and bulk of switches

- CHANGELOG.rst
- tests/unit/test_match_13.py
- v0x04/match.py
Closes #196
Stored flows with empty `"match"` will not longer match every flows deletion with the same table ID.
Repeated the issue case
Updated unit tests
```
+ python3 -m pytest tests/ --reruns 2 -r fEr
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.5.0
rootdir: /tests
plugins: rerunfailures-13.0, timeout-2.2.0, anyio-4.3.0
collected 277 items
tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  7%]
tests/test_e2e_06_topology.py ....                                       [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x....................... [ 23%]
. …
```
> Changed flows matches with empty "match"

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Closes #234
Added missing `by_switch` parameters
Unit test results.
```
tests/integration/test_main.py ..                                                                                                                                                                                                      [  1%]
tests/unit/test_barrier_request.py .                                                                                                                                                                                                   [  2%]
tests/unit/test_db_models.py ...                                                                                                                                                                                                       [  4%] …
```
> Added missing `by_switch` parameters
